kind: Deployment
apiVersion: apps/v1
metadata:
   name: pipdeploy
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: pipdeploy
   template:
      metadata:
        labels:
          app: pipdeploy
      spec:
       containers:
        - name: pipdeploy
          image: mehdibrahim/devops-integration
          imagePullPolicy: Always
          ports:
          - containerPort: 80